### ISSUE TITLE
ReferenceError: arc is not defined

### ISSUE THREAD

**Issue by oichidan** [quxios/QMV-Master-Demo#18]
I've encountered this bug while loading the demo to playtest.
![image](https://user-images.githubusercontent.com/16263389/41809893-49a064ea-771f-11e8-9a1b-e177a95ee9e9.png)

Here's a screenshot from the developer tools console.
![image](https://user-images.githubusercontent.com/16263389/41809896-543b6e90-771f-11e8-8406-af3f84c8347c.png)

Here's an excerpt from the developer tools console, if needed.

```
13/C:/Users/a9/Documents/MV/Project1/js/plugins/QPlus.js:224 Uncaught TypeError: undefined is not a function
https://quxios.github.io/data/pluginsMin.json Failed to load resource: net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH
rpg_managers.js:1722 ReferenceError: arc is not defined
    at Game_Event.eval (eval at <anonymous> (file:///C:/Users/a9/Documents/MV/Project1/js/rpg_objects.js:7060:20), <anonymous>:1:1)
    at Game_Event.Game_Character.processMoveCommand (file:///C:/Users/a9/Documents/MV/Project1/js/rpg_objects.js:7060:9)
    at Game_Event.Game_Character.updateRoutineMove (file:///C:/Users/a9/Documents/MV/Project1/js/rpg_objects.js:6914:18)
    at Game_Event.moveTypeCustom (file:///C:/Users/a9/Documents/MV/Project1/js/rpg_objects.js:8540:10)
    at Game_Event.updateSelfMovement (file:///C:/Users/a9/Documents/MV/Project1/js/rpg_objects.js:8491:18)
    at Game_Event.updateStop (file:///C:/Users/a9/Documents/MV/Project1/js/rpg_objects.js:8476:14)
    at Game_Event.Game_CharacterBase.update (file:///C:/Users/a9/Documents/MV/Project1/js/rpg_objects.js:6489:14)
    at Game_Event.Game_CharacterBase.update (file:///C:/Users/a9/Documents/MV/Project1/js/plugins/QYScale.js:168:37)
    at Game_Event.update (file:///C:/Users/a9/Documents/MV/Project1/js/rpg_objects.js:8706:37)
    at file:///C:/Users/a9/Documents/MV/Project1/js/rpg_objects.js:6033:15
```

**Comment by clorofolle** [comment]
I had this same issue just yesterday. Turned out I had an older version of rpgmaker mv installed. Installing the 1. 6. 1 version solved it!
